# Generated by Django 5.1 on 2024-08-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('year', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car2_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.carmodel')),
                ('carmarka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.marka')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.marka'),
        ),
    ]
